# Generated by Django 5.2 on 2025-04-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('COMMENCE', 'Commencé'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], default='COMMENCE', max_length=20)),
                ('pourcentage_completion', models.IntegerField(default=0)),
                ('derniere_activite', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
