# Generated by Django 5.2 on 2025-04-13 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apprentissage', '0001_initial'),
        ('ressources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progression',
            name='ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressources.ressource'),
        ),
    ]
