# Generated by Django 5.2 on 2025-04-13 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ressources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favori',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ressource',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressources.categorie'),
        ),
        migrations.AddField(
            model_name='ressource',
            name='createur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favori',
            name='ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressources.ressource'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressources.ressource'),
        ),
        migrations.AddField(
            model_name='telechargement',
            name='ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressources.ressource'),
        ),
        migrations.AddField(
            model_name='telechargement',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favori',
            unique_together={('utilisateur', 'ressource')},
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('utilisateur', 'ressource')},
        ),
        migrations.AlterUniqueTogether(
            name='telechargement',
            unique_together={('utilisateur', 'ressource')},
        ),
    ]
