# Generated by Django 5.2 on 2025-04-18 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
