# Generated by Django 5.2 on 2025-04-18 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0003_delete_categories'),
    ]

    operations = [
    ]
