# Generated by Django 5.2 on 2025-04-18 12:23

# ressources/migrations/0002_add_default_categories.py
from django.db import migrations

def add_default_categories(apps, schema_editor):
    Categorie = apps.get_model('ressources', 'Categorie')
    categories = [
        {'nom': 'Mathématiques', 'description': 'Cours et exercices de mathématiques'},
        {'nom': 'Physique-Chimie', 'description': 'Ressources en physique et chimie'},
        {'nom': 'Français', 'description': 'Littérature et grammaire'},
        {'nom': 'Histoire-Géographie', 'description': 'Cours d\'histoire et géographie'},
        {'nom': 'SVT', 'description': 'Sciences de la vie et de la Terre'},
    ]
    for cat in categories:
        Categorie.objects.create(**cat)

class Migration(migrations.Migration):
    dependencies = [
        ('ressources', '0001_initial'),  # Dépend de la migration initiale
    ]

    operations = [
        migrations.RunPython(add_default_categories),
    ]