# Generated by Django 5.2 on 2025-04-18 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0004_auto_20250418_1217'),
        ('ressources', '0005_add_default_categories'),
    ]

    operations = [
    ]
